//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniCore.Modules.FMMS.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FmmsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FmmsResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmniCore.Modules.FMMS.Resources.Languages.FmmsResources", typeof(FmmsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compressed Size.
        /// </summary>
        public static string Column_CompressedSize {
            get {
                return ResourceManager.GetString("Column_CompressedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension.
        /// </summary>
        public static string Column_Extension {
            get {
                return ResourceManager.GetString("Column_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full Path.
        /// </summary>
        public static string Column_FullPath {
            get {
                return ResourceManager.GetString("Column_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string Column_Id {
            get {
                return ResourceManager.GetString("Column_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Archive.
        /// </summary>
        public static string Column_IsArchive {
            get {
                return ResourceManager.GetString("Column_IsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Archive Entry.
        /// </summary>
        public static string Column_IsArchiveEntry {
            get {
                return ResourceManager.GetString("Column_IsArchiveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MD5 Hash.
        /// </summary>
        public static string Column_MD5 {
            get {
                return ResourceManager.GetString("Column_MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Name.
        /// </summary>
        public static string Column_Name {
            get {
                return ResourceManager.GetString("Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pages Count.
        /// </summary>
        public static string Column_PagesCount {
            get {
                return ResourceManager.GetString("Column_PagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SHA-256 Hash.
        /// </summary>
        public static string Column_SHA256 {
            get {
                return ResourceManager.GetString("Column_SHA256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SHA-512 Hash.
        /// </summary>
        public static string Column_SHA512 {
            get {
                return ResourceManager.GetString("Column_SHA512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        public static string Column_Size {
            get {
                return ResourceManager.GetString("Column_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uncompressed Size.
        /// </summary>
        public static string Column_UnCompressedSize {
            get {
                return ResourceManager.GetString("Column_UnCompressedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copied to clipboard.
        /// </summary>
        public static string Common_Copied {
            get {
                return ResourceManager.GetString("Common_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Settings.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy Info.
        /// </summary>
        public static string Menu_Copy_Info {
            get {
                return ResourceManager.GetString("Menu_Copy_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy All Selected Info.
        /// </summary>
        public static string Menu_Copy_Info_All {
            get {
                return ResourceManager.GetString("Menu_Copy_Info_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy Info as TSV.
        /// </summary>
        public static string Menu_Copy_Info_TSV {
            get {
                return ResourceManager.GetString("Menu_Copy_Info_TSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy All Selected as TSV.
        /// </summary>
        public static string Menu_Copy_Info_TSV_All {
            get {
                return ResourceManager.GetString("Menu_Copy_Info_TSV_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open File.
        /// </summary>
        public static string Menu_Open_File {
            get {
                return ResourceManager.GetString("Menu_Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Folder Location.
        /// </summary>
        public static string Menu_Open_Folder {
            get {
                return ResourceManager.GetString("Menu_Open_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File and metadata analysis.
        /// </summary>
        public static string ModuleDescription {
            get {
                return ResourceManager.GetString("ModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FMMS.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Obtaining various metadata about files.
        /// </summary>
        public static string Page_Files_Scanner_Description {
            get {
                return ResourceManager.GetString("Page_Files_Scanner_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File analysis.
        /// </summary>
        public static string Page_Files_Scanner_Title {
            get {
                return ResourceManager.GetString("Page_Files_Scanner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Getting a list of files and folders inside folders.
        /// </summary>
        public static string Page_Folder_Scanner_Description {
            get {
                return ResourceManager.GetString("Page_Folder_Scanner_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disk analysis.
        /// </summary>
        public static string Page_Folder_Scanner_Title {
            get {
                return ResourceManager.GetString("Page_Folder_Scanner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Scanner_Cancel {
            get {
                return ResourceManager.GetString("Scanner_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scanning cancelled.
        /// </summary>
        public static string Scanner_Cancelled {
            get {
                return ResourceManager.GetString("Scanner_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scanning completed successfully.
        /// </summary>
        public static string Scanner_Completed_Success {
            get {
                return ResourceManager.GetString("Scanner_Completed_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder path.
        /// </summary>
        public static string Scanner_FolderPath {
            get {
                return ResourceManager.GetString("Scanner_FolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select folder.
        /// </summary>
        public static string Scanner_SelectFolder {
            get {
                return ResourceManager.GetString("Scanner_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start scanning.
        /// </summary>
        public static string Scanner_Start {
            get {
                return ResourceManager.GetString("Scanner_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archive Extensions.
        /// </summary>
        public static string Settings_Archives_Title {
            get {
                return ResourceManager.GetString("Settings_Archives_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select which data to display in the main scanning window.
        /// </summary>
        public static string Settings_Columns_Description {
            get {
                return ResourceManager.GetString("Settings_Columns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Column Visibility.
        /// </summary>
        public static string Settings_Columns_Title {
            get {
                return ResourceManager.GetString("Settings_Columns_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press Enter to add a new extension.
        /// </summary>
        public static string Settings_CustomArchiveExtensions_Helper {
            get {
                return ResourceManager.GetString("Settings_CustomArchiveExtensions_Helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add extensions that the application should treat as archives (e.g., .apk, .epub)..
        /// </summary>
        public static string Settings_CustomArchiveExtensions_Hint {
            get {
                return ResourceManager.GetString("Settings_CustomArchiveExtensions_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Extensions.
        /// </summary>
        public static string Settings_CustomArchiveExtensions_Label {
            get {
                return ResourceManager.GetString("Settings_CustomArchiveExtensions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Displayed size unit.
        /// </summary>
        public static string Settings_DisplayedSizeType {
            get {
                return ResourceManager.GetString("Settings_DisplayedSizeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General Settings.
        /// </summary>
        public static string Settings_General_Title {
            get {
                return ResourceManager.GetString("Settings_General_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculate Hash Sums.
        /// </summary>
        public static string Settings_Hashing_Title {
            get {
                return ResourceManager.GetString("Settings_Hashing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No custom rules defined.
        /// </summary>
        public static string Settings_PagesRules_Empty {
            get {
                return ResourceManager.GetString("Settings_PagesRules_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension.
        /// </summary>
        public static string Settings_PagesRules_Extension {
            get {
                return ResourceManager.GetString("Settings_PagesRules_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom Page Count Rules.
        /// </summary>
        public static string Settings_PagesRules_Title {
            get {
                return ResourceManager.GetString("Settings_PagesRules_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string Settings_PagesRules_Value {
            get {
                return ResourceManager.GetString("Settings_PagesRules_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan archive contents.
        /// </summary>
        public static string Settings_ScanArchives {
            get {
                return ResourceManager.GetString("Settings_ScanArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bytes (B).
        /// </summary>
        public static string SizeType_B {
            get {
                return ResourceManager.GetString("SizeType_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gigabytes (GB).
        /// </summary>
        public static string SizeType_GB {
            get {
                return ResourceManager.GetString("SizeType_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kilobytes (KB).
        /// </summary>
        public static string SizeType_KB {
            get {
                return ResourceManager.GetString("SizeType_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Megabytes (MB).
        /// </summary>
        public static string SizeType_MB {
            get {
                return ResourceManager.GetString("SizeType_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compressed Size.
        /// </summary>
        public static string Table_Compressed_Size {
            get {
                return ResourceManager.GetString("Table_Compressed_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension.
        /// </summary>
        public static string Table_Extension {
            get {
                return ResourceManager.GetString("Table_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full Path.
        /// </summary>
        public static string Table_Full_Path {
            get {
                return ResourceManager.GetString("Table_Full_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string Table_Id {
            get {
                return ResourceManager.GetString("Table_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Archive.
        /// </summary>
        public static string Table_Is_Archive {
            get {
                return ResourceManager.GetString("Table_Is_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Archive Entry.
        /// </summary>
        public static string Table_Is_Archive_Entry {
            get {
                return ResourceManager.GetString("Table_Is_Archive_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MD5.
        /// </summary>
        public static string Table_MD5 {
            get {
                return ResourceManager.GetString("Table_MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Table_Name {
            get {
                return ResourceManager.GetString("Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pages Count.
        /// </summary>
        public static string Table_Pages_Count {
            get {
                return ResourceManager.GetString("Table_Pages_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SHA-256.
        /// </summary>
        public static string Table_SHA256 {
            get {
                return ResourceManager.GetString("Table_SHA256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SHA-512.
        /// </summary>
        public static string Table_SHA512 {
            get {
                return ResourceManager.GetString("Table_SHA512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        public static string Table_Size {
            get {
                return ResourceManager.GetString("Table_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uncompressed Size.
        /// </summary>
        public static string Table_UnCompressed_Size {
            get {
                return ResourceManager.GetString("Table_UnCompressed_Size", resourceCulture);
            }
        }
    }
}
